# Generated by Django 3.2.5 on 2021-08-03 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210803_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 14, 26, 15, 1859, tzinfo=utc)),
        ),
    ]
