# Generated by Django 3.2.5 on 2021-08-04 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 6, 40, 15, 929374, tzinfo=utc)),
        ),
    ]
