# Generated by Django 3.2.5 on 2021-07-28 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 12, 3, 34, 412301, tzinfo=utc)),
        ),
    ]
