# Generated by Django 3.2.6 on 2021-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracurricular',
            name='hobbies_k',
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='hobby',
            field=models.TextField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='academic_achievements',
            field=models.TextField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='certificates',
            field=models.TextField(blank=True, default='None', max_length=100),
        ),
    ]
