# Generated by Django 3.2.5 on 2021-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0002_auto_20210817_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='cemailid',
            new_name='college_email_id',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='sapid',
            new_name='cv',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='gitprofurl',
            new_name='git_profile_url',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='linkedinprofurl',
            new_name='linkedin_profile_url',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='mobilenumber',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='pemailid',
            new_name='personal_email_id',
        ),
        migrations.AddField(
            model_name='cv',
            name='sap_id',
            field=models.IntegerField(blank=True, default=70472017099),
            preserve_default=False,
        ),
    ]
