# Generated by Django 3.2.6 on 2021-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0002_auto_20210820_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='academic_achievements',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='certificates',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='hobby',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='core_skills',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='programming_languages',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='tools_familiar_with',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
