# Generated by Django 3.2.5 on 2021-08-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0003_auto_20210817_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='mobile_number',
            field=models.IntegerField(blank=True),
        ),
    ]
