# Generated by Django 3.2.5 on 2021-08-17 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvg', '0004_auto_20210817_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='cv',
        ),
        migrations.AlterField(
            model_name='cv',
            name='sap_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
