# Generated by Django 3.2.5 on 2021-08-02 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0004_alter_cv_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 14, 11, 47, 342752, tzinfo=utc)),
        ),
    ]
