# Generated by Django 3.2.5 on 2021-08-17 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvg', '0005_auto_20210817_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='sap_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
