# Generated by Django 3.2.5 on 2021-08-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0009_alter_cv_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=20),
        ),
    ]
