# Generated by Django 3.2.5 on 2021-08-03 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0010_auto_20210803_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cv',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 14, 28, 35, 54472, tzinfo=utc)),
        ),
    ]
