# Generated by Django 3.2.5 on 2021-08-18 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvg', '0011_alter_cv_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='cv',
            name='sap_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
