# Generated by Django 3.2.5 on 2021-08-03 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0011_auto_20210803_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 15, 18, 38, 510339, tzinfo=utc)),
        ),
    ]
