# Generated by Django 3.2.5 on 2021-08-18 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvg', '0012_auto_20210818_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cv',
            name='edited_by',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='cv',
            name='sap_id',
            field=models.CharField(max_length=11),
        ),
    ]
