# Generated by Django 3.2.5 on 2021-08-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0015_auto_20210818_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='sap_id',
            field=models.IntegerField(max_length=11),
        ),
    ]
