# Generated by Django 3.2.5 on 2021-08-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0016_alter_cv_sap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='sap_id',
            field=models.IntegerField(unique=True),
        ),
    ]
