# Generated by Django 3.2.5 on 2021-08-18 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0019_auto_20210818_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='academics',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
