# Generated by Django 3.2.5 on 2021-08-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0020_auto_20210818_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='academics',
            name='tenth_percentile',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='academics',
            name='twelvth_percentile',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
