# Generated by Django 3.2.6 on 2021-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvg', '0022_auto_20210819_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academics',
            old_name='twelvth_percentile',
            new_name='twelfth_percentile',
        ),
        migrations.AlterField(
            model_name='cv',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Bisexual', 'Bisexual'), ('None', 'None')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='internships',
            name='endmonth',
            field=models.IntegerField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='internships',
            name='startmonth',
            field=models.IntegerField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='endmonth',
            field=models.IntegerField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='startmonth',
            field=models.IntegerField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roles',
            name='endmonth',
            field=models.IntegerField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roles',
            name='startmonth',
            field=models.IntegerField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
    ]
